### ISSUE TITLE
DrawEM atlas registration: Value of term NMI is NaN

### ISSUE THREAD

**Issue by kkapse5891** [BioMedIA/MIRTK#587] opened 2017-06-14 18:38 UTC
Hi,

I am applying mirtk register and i am getting following error.
RegistrationEnergy::Value Value of term NMI is NaN!!

Can you guys please help in understanding the source of error and possible approaches/solutions?

Thanks in advance
KK

**Comment by schuhschuh** [comment] 2017-06-14 18:44
Hi @kkapse5891,

this likely means that your images are not overlapping, i.e., there are no samples from which to estimate the joint probability distribution. It would be useful if you provide at a minimum the command you run and attach any parameter file if you use one. You can further run the command with the `-v 3` option to get verbose output, and `-debug` option to have it write files to your current working directory (file name prefix is `mirtk_`) which help to identify the problem.

To see if the images overlap, load them in the viewer: `mirtk view target.nii.gz source.nii.gz`. You get the binary for Linux or macOS [here](https://bintray.com/schuhschuh/generic/MIRTKViewer).

Andreas

**Comment by kkapse5891** [comment] 2017-07-07 17:08
Hi Schuhschuh,

Thanks for your response. 
I am running drawem neonatal pipeline v1.1.sh
it failed during 'register-multi-atlas-using-gm-posteriors.sh'
i am running neonatal brain segmentation of a 3D brain image reconstructed from 2D SSFSE

Please let me know your feedback

Best
KK

**Comment by schuhschuh** [comment] 2017-07-07 17:11
Without more details on where exactly it failed and why some investigation as suggested previously regarding the content of the input images to the registration step that fails, it will be hard to track down the issue. Otherwise, I also suggest you seek some help from @amakropoulos who developed the Draw-EM pipeline.

**Comment by kkapse5891** [comment] 2017-07-07 18:01
[0707.docx](https://github.com/BioMedIA/MIRTK/files/1131856/0707.docx)

Hi,

I have attached the word doc that output log file info from register-multi-atlas-using-gm-posteriors.sh
it ends at resolution level 4 'Registration with similarity transformation model'

on page-13 'log/recon-err', you will see the exact error as earlier. 

Below is the command from the log that it fails at. 

mirtk register N4/<input.nii.gz> /cm/shared/apps/mirtk/Packages/DrawEM/atlases/ALBERTs/T2/ALBERT_02.nii.gz segmentations-data/gm-posteriors/<input.nii.gz> /cm/shared/apps/mirtk/Packages/DrawEM/atlases/ALBERTs/gm-posteriors-v3/ALBERT_02.nii.gz -parin /cm/shared/apps/mirtk/Packages/DrawEM/parameters/ireg-multichannel-structural.cfg -dofout dofs/input-ALBERT_02-n.dof.gz -threads 1

Please take a look and let me know your feedback
If the images are not overlapping, what would be an alternative approach? 
I appreciate your feedback on this

Best
KK

**Comment by schuhschuh** [comment] 2017-07-11 18:15
To isolate the problem from the Draw-EM pipeline, can you copy the following files in a new empty directory, e.g., `MIRTK_DrawEM_Issue_587`:

- `N4/onesie_1z017_01_recon_050.nii.gz`
- `segmentations-data/gm-posteriors/onesie_1z017_01_recon_050.nii.gz` --> `onesie_1z017_01_recon_050_gm.nii.gz`
- `/cm/shared/apps/mirtk/Packages/DrawEM/atlases/ALBERTs/T2/ALBERT_02.nii.gz`
- `/cm/shared/apps/mirtk/Packages/DrawEM/atlases/ALBERTs/gm-posteriors-v3/ALBERT_02.nii.gz` --> `ALBERT_02_gm.nii.gz`
- `/cm/shared/apps/mirtk/Packages/DrawEM/parameters/ireg-multichannel-structural.cfg`

and then run the following command to first reproduce the error:

```shell
cd MIRTK_DrawEM_Issue_587
mirtk register onesie_1z017_01_recon_050.nii.gz ALBERT_02.nii.gz onesie_1z017_01_recon_050_gm.nii.gz ALBERT_02_gm.nii.gz -parin ireg-multichannel-structural.cfg -dofout out.dof.gz -threads 1
```

You can then run this command also with `-debug 3` option. This will write a number of files to the current working directory with prefix `mirtk_`. These may help to debug the issue further. It would also be useful if you would be able to share these files, e.g., in a private message.

**Comment by schuhschuh** [comment] 2017-07-11 18:16
You could drop off the files for us at https://icseclzt.cc.ic.ac.uk/verify.php.
Recipient: `andreas.schuh@imperial.ac.uk`.

**Comment by schuhschuh** [comment] 2017-07-17 18:27
@kkapse5891 Thanks for sharing your files. Unfortunately I cannot reproduce the error with these images. Have you tried to reproduce it on your machine? Are you certain these are the input files of the registration within the Draw-EM pipeline?

See `register` command output:
```
as12312@cotopaxi:/Users/as12312/Testing/MIRTK/mirtk_drawem_issue_587
> mirtk register onesie_1z017_01_recon_050.nii.gz ALBERT_02.nii.gz onesie_1z017_01_recon_050_gm.nii.gz ALBERT_02_gm.nii.gz -parin ireg-multichannel-structural.cfg -dofout out2.dof.gz -threads 1
register  (rev b1fcaf2, built on Jul 17 2017)


Registration with similarity transformation model

Resolution level 4

          Energy                    NMI                         GM Sim               Bending energy
   1      1.00000     =  0.25000 (     1.00501    ) +  0.75000 (     0.12975    ) +       0.00000
   2      0.56038     =  0.24846 (     1.01115    ) +  0.31193 (     0.05396    ) +       0.00000
   3      0.54897     =  0.24757 (     1.01469    ) +  0.30140 (     0.05214    ) +       0.00000
   4      0.54891     =  0.24746 (     1.01513    ) +  0.30145 (     0.05215    ) +       0.00000
   5      0.54875     =  0.24742 (     1.01528    ) +  0.30133 (     0.05213    ) +       0.00000

Resolution level 3

          Energy                    NMI                         GM Sim               Bending energy
   1      1.00000     =  0.25000 (     1.00689    ) +  0.75000 (     0.07469    ) +       0.00000

Resolution level 2

          Energy                    NMI                         GM Sim               Bending energy
   1      1.00000     =  0.25000 (     1.00394    ) +  0.75000 (     0.11252    ) +       0.00000

Resolution level 1

          Energy                    NMI                         GM Sim               Bending energy
   1      1.00000     =  0.25000 (     1.00265    ) +  0.75000 (     0.15345    ) +       0.00000


Final similarity transformation:

    tx  =  -1.5030  ty  = -32.1222  tz  =  -0.3798
    rx  =  -5.4283  ry  =   8.3513  rz  =  -2.4302
    s   = 244.7302



Registration with affine transformation model

Resolution level 4

          Energy                    NMI                         GM Sim               Bending energy
   1      1.00000     =  0.25000 (     1.01534    ) +  0.75000 (     0.05220    ) +       0.00000
   2      0.99727     =  0.25018 (     1.01464    ) +  0.74709 (     0.05199    ) +       0.00000
   3      0.99094     =  0.24964 (     1.01675    ) +  0.74129 (     0.05159    ) +       0.00000
   4      0.98985     =  0.24963 (     1.01679    ) +  0.74021 (     0.05152    ) +       0.00000

Resolution level 3

          Energy                    NMI                         GM Sim               Bending energy
   1      1.00000     =  0.25000 (     1.00712    ) +  0.75000 (     0.07773    ) +       0.00000
   2      0.99363     =  0.24967 (     1.00841    ) +  0.74395 (     0.07711    ) +       0.00000
   3      0.98243     =  0.24923 (     1.01016    ) +  0.73320 (     0.07599    ) +       0.00000
   4      0.98223     =  0.24923 (     1.01018    ) +  0.73301 (     0.07597    ) +       0.00000

Resolution level 2

          Energy                    NMI                         GM Sim               Bending energy
   1      1.00000     =  0.25000 (     1.00605    ) +  0.75000 (     0.11853    ) +       0.00000
   2      0.99981     =  0.24998 (     1.00613    ) +  0.74983 (     0.11850    ) +       0.00000

Resolution level 1

          Energy                    NMI                         GM Sim               Bending energy
   1      1.00000     =  0.25000 (     1.00398    ) +  0.75000 (     0.16364    ) +       0.00000
   2      0.99983     =  0.24999 (     1.00401    ) +  0.74984 (     0.16360    ) +       0.00000


Final affine transformation:

    tx  = -11.7558  ty  = -30.4665  tz  = -27.7025
    rx  = -15.6880  ry  =   1.6311  rz  =  -3.9234
    sx  = 247.1637  sy  = 253.1358  sz  = 251.7876
    sxy =  -2.0521  syz =   7.0889  sxz =   1.9078



Registration with free-form deformation model

Resolution level 4

          Energy                    NMI                         GM Sim               Bending energy
   1      1.00000     =  0.25000 (     1.01867    ) +  0.75000 (     0.05078    ) +       0.00000
   2      0.99947     =  0.24973 (     1.01975    ) +  0.73516 (     0.04978    ) +       0.01458

Resolution level 3

          Energy                    NMI                         GM Sim               Bending energy
   1      1.00087     =  0.25000 (     1.01024    ) +  0.75000 (     0.07519    ) +       0.00087
   2      0.97394     =  0.24939 (     1.01266    ) +  0.69726 (     0.06990    ) +       0.02729
   3      0.96951     =  0.24904 (     1.01404    ) +  0.68169 (     0.06834    ) +       0.03878
   4      0.96644     =  0.24897 (     1.01431    ) +  0.68305 (     0.06848    ) +       0.03442

Resolution level 2

          Energy                    NMI                         GM Sim               Bending energy
   1      1.00364     =  0.25000 (     1.00962    ) +  0.75000 (     0.10846    ) +       0.00364
   2      0.94621     =  0.24891 (     1.01394    ) +  0.66484 (     0.09615    ) +       0.03246
   3      0.92765     =  0.24794 (     1.01779    ) +  0.62486 (     0.09037    ) +       0.05485
   4      0.91655     =  0.24741 (     1.01987    ) +  0.60095 (     0.08691    ) +       0.06819
   5      0.91141     =  0.24696 (     1.02165    ) +  0.58398 (     0.08445    ) +       0.08046
   6      0.90720     =  0.24664 (     1.02294    ) +  0.57223 (     0.08275    ) +       0.08834
   7      0.90413     =  0.24637 (     1.02401    ) +  0.56486 (     0.08169    ) +       0.09290
   8      0.90138     =  0.24621 (     1.02462    ) +  0.56296 (     0.08141    ) +       0.09220
   9      0.89922     =  0.24611 (     1.02503    ) +  0.56128 (     0.08117    ) +       0.09183
  10      0.89856     =  0.24603 (     1.02533    ) +  0.56006 (     0.08099    ) +       0.09246
  11      0.89786     =  0.24598 (     1.02556    ) +  0.55958 (     0.08093    ) +       0.09231
  12      0.89692     =  0.24590 (     1.02588    ) +  0.55757 (     0.08064    ) +       0.09345
  13      0.89593     =  0.24579 (     1.02629    ) +  0.55437 (     0.08017    ) +       0.09576
  14      0.89514     =  0.24557 (     1.02717    ) +  0.54941 (     0.07945    ) +       0.10016
  15      0.89397     =  0.24537 (     1.02797    ) +  0.54389 (     0.07866    ) +       0.10471
  16      0.89323     =  0.24531 (     1.02821    ) +  0.54268 (     0.07848    ) +       0.10524
  17      0.89314     =  0.24523 (     1.02852    ) +  0.54236 (     0.07843    ) +       0.10555
  18      0.89284     =  0.24520 (     1.02864    ) +  0.54160 (     0.07833    ) +       0.10604
  19      0.89196     =  0.24500 (     1.02942    ) +  0.53772 (     0.07776    ) +       0.10923
  20      0.89150     =  0.24485 (     1.03002    ) +  0.53411 (     0.07724    ) +       0.11254
  21      0.89003     =  0.24470 (     1.03060    ) +  0.52885 (     0.07648    ) +       0.11648

Resolution level 1

          Energy                    NMI                         GM Sim               Bending energy
   1      1.01038     =  0.25000 (     1.02405    ) +  0.75000 (     0.11325    ) +       0.01038
   2      0.91822     =  0.24786 (     1.03239    ) +  0.64048 (     0.09671    ) +       0.02988
   3      0.87194     =  0.24570 (     1.04084    ) +  0.56811 (     0.08579    ) +       0.05812
   4      0.84299     =  0.24422 (     1.04662    ) +  0.52860 (     0.07982    ) +       0.07017
   5      0.82495     =  0.24313 (     1.05088    ) +  0.50276 (     0.07592    ) +       0.07906
   6      0.81210     =  0.24229 (     1.05416    ) +  0.48437 (     0.07314    ) +       0.08545
   7      0.80031     =  0.24157 (     1.05696    ) +  0.46794 (     0.07066    ) +       0.09081
   8      0.79231     =  0.24092 (     1.05951    ) +  0.45479 (     0.06867    ) +       0.09661
   9      0.78436     =  0.24032 (     1.06186    ) +  0.44383 (     0.06702    ) +       0.10021
  10      0.77845     =  0.23976 (     1.06403    ) +  0.43400 (     0.06553    ) +       0.10469
  11      0.77246     =  0.23932 (     1.06574    ) +  0.42634 (     0.06438    ) +       0.10680
  12      0.76868     =  0.23901 (     1.06694    ) +  0.42182 (     0.06369    ) +       0.10785
  13      0.76486     =  0.23879 (     1.06782    ) +  0.41667 (     0.06292    ) +       0.10940
  14      0.76098     =  0.23849 (     1.06898    ) +  0.41222 (     0.06225    ) +       0.11027
  15      0.75820     =  0.23823 (     1.06999    ) +  0.40833 (     0.06166    ) +       0.11164
  16      0.75462     =  0.23797 (     1.07102    ) +  0.40413 (     0.06102    ) +       0.11252
  17      0.75198     =  0.23776 (     1.07181    ) +  0.40083 (     0.06052    ) +       0.11339
  18      0.75020     =  0.23763 (     1.07233    ) +  0.39909 (     0.06026    ) +       0.11348
  19      0.74899     =  0.23756 (     1.07262    ) +  0.39791 (     0.06008    ) +       0.11353
  20      0.74725     =  0.23742 (     1.07317    ) +  0.39554 (     0.05973    ) +       0.11429
  21      0.74404     =  0.23716 (     1.07419    ) +  0.39099 (     0.05904    ) +       0.11589
  22      0.74112     =  0.23689 (     1.07524    ) +  0.38653 (     0.05837    ) +       0.11771
  23      0.73886     =  0.23664 (     1.07619    ) +  0.38264 (     0.05778    ) +       0.11958
  24      0.73694     =  0.23639 (     1.07718    ) +  0.37935 (     0.05728    ) +       0.12120
  25      0.73511     =  0.23620 (     1.07792    ) +  0.37574 (     0.05674    ) +       0.12317
  26      0.73300     =  0.23601 (     1.07867    ) +  0.37322 (     0.05636    ) +       0.12377
  27      0.73206     =  0.23597 (     1.07880    ) +  0.37243 (     0.05624    ) +       0.12366
  28      0.73122     =  0.23593 (     1.07898    ) +  0.37160 (     0.05611    ) +       0.12369
  29      0.72976     =  0.23581 (     1.07944    ) +  0.37024 (     0.05591    ) +       0.12371
  30      0.72892     =  0.23574 (     1.07972    ) +  0.36940 (     0.05578    ) +       0.12378
  31      0.72819     =  0.23567 (     1.07998    ) +  0.36848 (     0.05564    ) +       0.12404
  32      0.72680     =  0.23554 (     1.08048    ) +  0.36680 (     0.05539    ) +       0.12445
  33      0.72592     =  0.23547 (     1.08077    ) +  0.36550 (     0.05519    ) +       0.12495
  34      0.72404     =  0.23525 (     1.08164    ) +  0.36227 (     0.05470    ) +       0.12653
  35      0.72240     =  0.23503 (     1.08250    ) +  0.35945 (     0.05428    ) +       0.12792
  36      0.72118     =  0.23487 (     1.08313    ) +  0.35707 (     0.05392    ) +       0.12924
  37      0.72006     =  0.23475 (     1.08360    ) +  0.35540 (     0.05367    ) +       0.12992
  38      0.71900     =  0.23464 (     1.08401    ) +  0.35406 (     0.05346    ) +       0.13030
  39      0.71771     =  0.23454 (     1.08439    ) +  0.35230 (     0.05320    ) +       0.13087
  40      0.71664     =  0.23437 (     1.08505    ) +  0.34960 (     0.05279    ) +       0.13266
  41      0.71509     =  0.23418 (     1.08580    ) +  0.34715 (     0.05242    ) +       0.13376
  42      0.71374     =  0.23401 (     1.08647    ) +  0.34497 (     0.05209    ) +       0.13476
  43      0.71259     =  0.23391 (     1.08686    ) +  0.34346 (     0.05186    ) +       0.13522
  44      0.71119     =  0.23380 (     1.08729    ) +  0.34168 (     0.05159    ) +       0.13571
  45      0.71015     =  0.23370 (     1.08770    ) +  0.34029 (     0.05138    ) +       0.13616
  46      0.70894     =  0.23360 (     1.08807    ) +  0.33867 (     0.05114    ) +       0.13668
  47      0.70797     =  0.23350 (     1.08847    ) +  0.33742 (     0.05095    ) +       0.13705
  48      0.70751     =  0.23345 (     1.08865    ) +  0.33689 (     0.05087    ) +       0.13717
  49      0.70707     =  0.23340 (     1.08886    ) +  0.33633 (     0.05079    ) +       0.13735
  50      0.70609     =  0.23333 (     1.08912    ) +  0.33544 (     0.05065    ) +       0.13732
  51      0.70582     =  0.23332 (     1.08915    ) +  0.33514 (     0.05061    ) +       0.13736
  52      0.70486     =  0.23325 (     1.08943    ) +  0.33421 (     0.05047    ) +       0.13740
  53      0.70464     =  0.23322 (     1.08957    ) +  0.33402 (     0.05044    ) +       0.13741
  54      0.70449     =  0.23320 (     1.08964    ) +  0.33385 (     0.05041    ) +       0.13744
  55      0.70398     =  0.23316 (     1.08979    ) +  0.33338 (     0.05034    ) +       0.13744
  56      0.70387     =  0.23315 (     1.08984    ) +  0.33325 (     0.05032    ) +       0.13747
  57      0.70349     =  0.23313 (     1.08992    ) +  0.33273 (     0.05024    ) +       0.13763
  58      0.70279     =  0.23305 (     1.09023    ) +  0.33188 (     0.05011    ) +       0.13787
  59      0.70238     =  0.23301 (     1.09038    ) +  0.33121 (     0.05001    ) +       0.13817
  60      0.70171     =  0.23293 (     1.09069    ) +  0.33030 (     0.04988    ) +       0.13847
  61      0.70114     =  0.23287 (     1.09092    ) +  0.32941 (     0.04974    ) +       0.13886
  62      0.70030     =  0.23277 (     1.09130    ) +  0.32825 (     0.04957    ) +       0.13929
  63      0.70023     =  0.23274 (     1.09142    ) +  0.32784 (     0.04950    ) +       0.13964

CPU time is  0 h 11 min 59 sec
Finished in  0 h 12 min  0 sec
```

**Comment by kkapse5891** [comment] 2017-07-17 18:57
Hi,

Thanks for your suggestion. I have dropped the respective files into the above location. Please let me know your feedback

KK

**Comment by schuhschuh** [comment] 2017-07-18 10:51
@kkapse5891 Please see my [previous comment](https://github.com/BioMedIA/MIRTK/issues/587#issuecomment-315840378). When you run the same command that I posted in the directory with the files that you send me, do you still get the reported error? It was working fine for me with these files.

**Comment by kkapse5891** [comment] 2017-07-18 17:08
Hi,
Yes. It runs fine with your suggested commandline and it successfully completes the registration. But when i am running the same analysis in drawmem script::
/mirtk/Packages/DrawEM/pipelines/neonatal-pipeline-v1.1.sh <3D_T2.nii.gz> <age>

it fails and gives error 'RegistrationEnergy::Value: Value of term NMI is NaN!'
Error: register command returned non-zero exit status 1

I have attached both the log files that drawem pipeline provides during the segmentation process. 'drawem_1z017_01_err.txt' will give an error for the command while 'drawem_1z017_01.txt' will provide detailed verbose of the commands utilized till it fails. Please take a look and let me know your feedback

Thanks for your valued insight in this. 

Following 
[drawem_1z017_01.txt](https://github.com/BioMedIA/MIRTK/files/1156692/drawem_1z017_01.txt)
[drawem_1z017_01_err.txt](https://github.com/BioMedIA/MIRTK/files/1156693/drawem_1z017_01_err.txt)

**Comment by schuhschuh** [comment] 2017-07-19 09:05
Thanks for confirming. Then let's try further to reproduce the error during the Draw-EM pipeline execution. From the log files you posted, I can see that the following command caused the error:

```
mirtk register \
    N4/onesie_1z017_01_recon_050.nii.gz \
    /cm/shared/apps/mirtk/Packages/DrawEM/atlases/ALBERTs/T2/ALBERT_02.nii.gz \
    segmentations-data/gm-posteriors/onesie_1z017_01_recon_050.nii.gz \
    /cm/shared/apps/mirtk/Packages/DrawEM/atlases/ALBERTs/gm-posteriors-v3/ALBERT_02.nii.gz \
    -parin /cm/shared/apps/mirtk/Packages/DrawEM/parameters/ireg-multichannel-structural.cfg \
    -dofout dofs/onesie_1z017_01_recon_050-ALBERT_02-n.dof.gz \
    -threads 1
```

When this happens, do the respective input files `N4/onesie_1z017_01_recon_050.nii.gz` and `segmentations-data/gm-posteriors/onesie_1z017_01_recon_050.nii.gz` still exist in the Draw-EM `-d`/`-data-dir` directory, i.e., by default the directory in which you executed `neonatal-pipeline-v1.1.sh`?

Can you copy and paste the above command in a terminal while being in this directory and see if you get the same error when running only this single registration command manually?

When yes, can you make sure to copy the actual files `N4/onesie_1z017_01_recon_050.nii.gz` and `segmentations-data/gm-posteriors/onesie_1z017_01_recon_050.nii.gz` and send them over? Are you certain that the previous images you've sent were indeed these images that are preprocessed by Draw-EM and not the original input files? I am asking so we can be sure that we can exclude the N4 step of being related to the error.

If the above command when executed right after `neonatal-pipeline-v1.1.sh` itself failed does work fine when you re-run it manually, it's going to be more difficult to isolate the problem...

**Comment by schuhschuh** [comment] 2017-07-19 09:48
@kkapse5891 I've just discovered something. From the logs I can tell that the registration of the first atlas `ALBERT_01` was successful, hence, assuming that the N4 corrected image is fine. Then I looked at the `ALBERT_02.nii.gz` image you sent me and noticed that it is not a T2-weighted image! Instead, both `ALBERT_02.nii.gz` and `ALBERT_02_gm.nii.gz` show the cortical grey matter probabilities. Can you verify this by looking at the images in the atlas directory that you downloaded from: https://www.doc.ic.ac.uk/~am411/atlases-DrawEM.html

**Comment by schuhschuh** [comment] 2017-07-19 09:51
I downloaded the atlases myself and had a look. These are fine. It appears you may have renamed the files incorrectly when you compiled the archive that you sent me earlier.

**Comment by schuhschuh** [comment] 2017-07-19 10:06
After replacing the correct T2-weighted image, the registration still succeeds without error.

Please check the `atlases/ALBERTs/T2/ALBERT_02.nii.gz` image that you have by opening it in a NIfTI image viewer if it is indeed a T2-weighted image or has somehow been overwritten incorrectly by one of the Draw-EM pipeline scripts.

When you are using Linux, consider also downloading the latest MIRTK version from:
https://bintray.com/schuhschuh/AppImages/MIRTK/master#files

```
wget -O mirtk https://bintray.com/schuhschuh/AppImages/download_file?file_path=MIRTK%2Bview-latest-x86_64-glibc2.15.AppImage
chmod a+x mirtk
```

And make sure this file is in a location of your `PATH` environment variable where it is found before the previous MIRTK installation. For example move it to `/usr/local/bin`:
```
sudo mv mirtk /usr/local/bin/
```

**Comment by schuhschuh** [comment] 2017-07-19 17:00
For the record, received new file drop off from @kkapse5891 with message:

> The attached file contains the output from the `neonatal-pipeline-v1.1.sh` for the subject i send earlier. It contains the the folder-outputs till it fails. I ran the following command you suggested from commandline and it still gives same error:
> 
> ```
> mirtk register \
>   N4/onesie_1z017_01_recon_050.nii.gz \
>   /cm/shared/apps/mirtk/Packages/DrawEM/atlases/ALBERTs/T2/ALBERT_02.nii.gz \
>   segmentations-data/gm-posteriors/onesie_1z017_01_recon_050.nii.gz \
>   /cm/shared/apps/mirtk/Packages/DrawEM/atlases/ALBERTs/gm-posteriors-v3/ALBERT_02.nii.gz \
>   -parin /cm/shared/apps/mirtk/Packages/DrawEM/parameters/ireg-multichannel-structural.cfg \
>   -dofout dofs/onesie_1z017_01_recon_050-ALBERT_02-n.dof.gz \
>   -threads 1
> ```
> 
> I also overlayed `segmentations-data/gm-posteriors/onesie_1z017_01_recon_050.nii.gz` onto `N4/onesie_1z017_01_recon_050.nii.gz` and they seem to be overlaying fine (by visual inspection). I would appreciate if you can take a look and let me know your feedback. I am surprised that this error is causing in only handful of the subject-scans as the data (3D T2 image) is used for all the subjects.

**Comment by schuhschuh** [comment] 2017-07-19 17:08
@kkapse5891 I've tried with the new files, but again the registration runs without error on my machine. Have you tried the latest MIRTK master HEAD revision as suggested in my previous message? Just to make sure the problem hasn't been fixed somehow in the meantime...

After downloading the new version and running the registration, if it fails please also post the output of `mirtk register -version` here.

**Comment by schuhschuh** [comment] 2017-07-19 17:13
PS: I am running it on macOS. Your `.zip` file contains `.DS_Store` files. Can I assume correctly that you are running MIRTK on macOS as well? In this case you can unfortunately not use the binary AppImage as suggested before...

**Comment by kkapse5891** [comment] 2017-07-24 15:21
Hi,

As you suggested i utilized latest mirtk and run the 'neonatal-pipeline-v1.1.sh'
So it successfully run 'Registration with similarity transformation model' but
it failed at 'mirtk normalize' with error 'Error: Missing executable for command: normalizeError: normalize command returned non-zero exit status 1'

Can you please suggest solution (missing executable) for this and maybe the cause of this error?

**Comment by schuhschuh** [comment] 2017-07-24 16:08
The `normalize` binary is part of the DrawEM module, which has to be enabled with CMake option `MODULE_DrawEM=ON`. The AppImage I suggested for Linux did not include this binary because of a mistake in the Travis CI script used to automatically build and update the file on bintray.com. I had not noticed this bug before, thanks for reporting it. It is fixed by PR #629.

For Linux, please re-download the latest MIRTK AppImage from bintray:
```
mirtk_app=MIRTK%2Bview-latest-x86_64-glibc2.15.AppImage && \
wget -O mirtk https://bintray.com/schuhschuh/AppImages/download_file?file_path=$mirtk_app && \
chmod a+x mirtk
```
(if you don't need the image viewer, use `mirtk_app=MIRTK-latest-x86_64-glibc2.14.AppImage`)

**Comment by kkapse5891** [comment] 2017-07-24 19:46
Hi,

Yes. After your suggestion of updating the latest mirtk (post-bug fix), the subjects that were failing the segmentation due to Value of NMI is NaN are now successfully segmented by drawem 'neonatal-pipeline-v1.1.sh'
I really appreciate for your support and suggestions on this error. Thank you!!

Best
KK

**Comment by schuhschuh** [comment] 2017-07-24 19:47
Great, glad it has been resolved.

**Closed by schuhschuh** 2017-07-24 19:47 UTC
